name: "Terraform CI Workflow"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-fmt-validate:
    name: "Terraform Format and Validation Check"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: "Initialize Terraform"
        run: terraform init

      - name: "Run terraform fmt"
        run: |
          if ! terraform fmt -check; then
            exit 1
          fi

      - name: "Run terraform validate"
        run: terraform validate
